### ISSUE TITLE
Error when uploading .xar file 

### ISSUE THREAD

**Issue by cwittern** [duncdrum/generator-exist#116]
Hi Duncan,
I built a .xar file from a project scaffolded with the generator, without any changes (using tei-publisher-simple).  When I import it into the database (5.0RC4) using the package manager, I get the following error:

`Error found while processing repo.xml: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: console:log [at line 67, column 1] `

Unfortunately, I have no idea where to look for the cause of this....

**Comment by duncdrum** [comment]
see #67 
I haven't been able to determin why tei-pub packages throws this error message. Its partially related to the state of Monex in the RC, and some weird race condition, there is no foul console:log command in repo.xml. 
Luckily the app still works as expected, so for now just ignore this. Sorry for the inconvenience.

**Comment by duncdrum** [comment]
thanks this was very helpful, this should be an easy fix.

**Comment by duncdrum** [comment]
@cwittern so the startup error are actually a separate bug, and still open. But i have fixed the incorrect paths, and another ticket open on gitlab. 
Once I added tests you should see a properly working tei-publisher style app, but given the intensive work for RC4 it might be a good idea to actually generate tei-publisher apps from within the main app, it ll take some time before i can make all the necesseary changes here once 4.0.0 is out.

**Comment by cwittern** [comment]
I see, thx for the heads-up.
